api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
<<<<<<< HEAD

=======
>>>>>>> f0bc670ff6fac107bca2b8c480789c913ee3f74c
    http_cache:
        invalidation:
            enabled: true
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
<<<<<<< HEAD
        public: true
=======
        public: true
>>>>>>> f0bc670ff6fac107bca2b8c480789c913ee3f74c
