nelmio_cors:
    defaults:
        allow_credentials: false 
        #allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
           # http://africemplois.herokuapp.com:80
    paths:
        '^/api/':
           # allow_origin: ['*']
            allow_headers: ['X-Requested-With', 'Content-Type', 'Origin', 'Authorization', 'Accept','Client-Security-Token', 'Accept-Encoding']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            #['^http://africemplois.herokuapp.com:80']
            #allow_origin: ['*']
            allow_headers: ['X-Requested-With', 'Content-Type', 'Origin', 'Authorization', 'Accept','Client-Security-Token', 'Accept-Encoding']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']
