nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(ACCESS_CONTROL_ALLOW_ORIGIN)%']
        allow_methods: ['%env(CORS_ALLOW_METHODS)%']
        allow_headers: ['%env(ALLOW_HEADERS)%']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
