#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        allow_headers: ['X-Requested-With', 'Content-Type', 'Origin', 'Authorization', 'Accept','Client-Security-Token', 'Accept-Encoding']
#        expose_headers: ['Link']
#max_age: 3600
#    paths:
#        '^/': ~


nelmio_cors:
    defaults:
        allow_credentials: false 
#        allow_origin: []
#        allow_headers: []
#        allow_methods: []
#        expose_headers: []
        max_age: 0
#        hosts: []
        origin_regex: false
        forced_allow_origin_value: '%env(CORS_FORCED_ALLOW_ORIGIN_VALUE)%'
           # http://africemplois.herokuapp.com:80
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['X-Requested-With', 'Content-Type', 'Origin', 'Authorization', 'Accept','Client-Security-Token', 'Accept-Encoding']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            #['^http://africemplois.herokuapp.com:80']
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['X-Requested-With', 'Content-Type', 'Origin', 'Authorization', 'Accept','Client-Security-Token', 'Accept-Encoding']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']