nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['X-Requested-With', 'Content-Type', 'Origin', 'Authorization', 'Accept','Client-Security-Token', 'Accept-Encoding']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~

