security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_ADMIN,ROLE_USER]

        #ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:

        login_phone:
            pattern:  ^/login_phone
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path: /login_phone
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #default_target_path: fos_user_security_login
                #use_referer: true
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }