vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            #uri_prefix: /media
            #upload_destination: '%kernel.project_dir%/public/media'

            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
