vich_uploader:
    db_driver: orm

    mappings:
        logo_entr:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
 
        user_cv:
            uri_prefix: /images/cv
            upload_destination: '%kernel.project_dir%/public/images/cv'

