<?php

namespace App\Repository;

use \Doctrine\ORM\EntityRepository;
/**
 * NiveauExperienceGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauExperienceGlobalRepository extends EntityRepository
{

}
