<?php

namespace App\Repository;

use \Doctrine\ORM\EntityRepository;
/**
 * NiveauEtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauEtudeRepository extends EntityRepository
{

}
