<?php

namespace App\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * SousSecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousSecteurRepository extends EntityRepository
{

    public function findListSearchSousSecteurs($motcle)
    {
        $qb=$this->createQueryBuilder('ssc')
            ->select('ssc')
            ->where('ssc.libelleSousSecteur like :libelleSousSecteur')
            ->setParameter('libelleSousSecteur', $motcle);
        return $qb->getQuery()->getResult();
    }


    /*

    public function getListSearchAgencesFrontend($name = NULL, $city = NULL)
    {
        $qb = $this->createQueryBuilder('ssc')
            ->leftJoin('ssc.secteur', 's')
            ->addSelect('s')
            ->Where('ssc.enabled = 1');

        if (!empty($city) ) {
            $qb->andWhere('ssc.city = :city')
                ->setParameter('city', $city);
        }
        if (!empty($name)) {
            $qb->andWhere('ssc.name LIKE :name')
                ->setParameter('name', '%'.$name.'%');
        }

        return $qb;
    }



*/














    /*


    public function getListSearchAgencesFrontend($name = NULL, $city = NULL)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.logo', 'l')
            ->addSelect('l')
            ->Where('a.enabled = 1');

        if (!empty($city) ) {
            $qb->andWhere('a.city = :city')
               ->setParameter('city', $city);
               }
              if (!empty($name)) {
            $qb->andWhere('a.name LIKE :name')
               ->setParameter('name', '%'.$name.'%');
              }

        return $qb;
    }









     */




}
